source "http://rubygems.org"

ruby '2.0.0'

# Add dependencies required to use your gem here.
# Example:
#   gem "activesupport", ">= 2.3.5"
gem "activerecord", "~> 4"
gem "holiday", :path => "../holiday"

# Add dependencies to develop your gem here.
# Include everything needed to run rake, tests, features, etc.
group :development, :test do
  gem "rspec", "~> 2.8.0"
  gem "rdoc", "~> 3.12"
  gem "jeweler", "~> 1.8.3"
  gem "sqlite3"
end
