source 'https://rubygems.org'

ruby '2.0.0'

gem 'rails', '4.0.0'

gem "holiday", :path => "../holiday"
gem "holiday_activerecord", :path => "../holiday_activerecord"
gem "sqlite3"

gem 'jquery-rails'

gem 'debugger', group: [:development]
