#!/usr/bin/env rake
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

HolidayApp::Application.load_tasks

desc "Migrate away!"
task "db:migrate" do
  #DUPLICATION with repository_config.rb! remove...
  ActiveRecord::Base.establish_connection(:adapter => "sqlite3", :database => "db/holiday_development.sqlite3")
  Holiday::ActiveRecordHolidayRepository.migrate
end