#!/usr/bin/env rake
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative 'config/application'

HolidayApp::Application.load_tasks

desc "Migrate away!"
task "db:migrate" => :setup do
  Holiday::ActiveRecordHolidayRepository.migrate
end

desc "Seed database with some data"
task "db:seed" => :setup do
  Holiday::EmployeeRepository.add(Holiday::Employee.new("foo@example.com"))
  Holiday::EmployeeRepository.add(Holiday::Employee.new("bar@example.com"))
end

task "setup" do
  require_relative 'config/initializers/repository_config'
end
