#!/usr/bin/env rake
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

HolidayApp::Application.load_tasks

desc "Migrate away!"
task "db:migrate" do
  #DUPLICATION with repository_config.rb! remove...
  ActiveRecord::Base.establish_connection(:adapter => "sqlite3", :database => "db/holiday_development.sqlite3")
  Holiday::ActiveRecordHolidayRepository.migrate
end

desc "Seed daabase with some data"
task "db:seed" do
  require File.join(File.dirname(__FILE__), 'config/initializers/repository_config')
  Holiday::EmployeeRepository.add(Holiday::Employee.new("foo@example.com"))
  Holiday::EmployeeRepository.add(Holiday::Employee.new("bar@example.com"))
end