source "http://rubygems.org"
# Add dependencies required to use your gem here.

gem "activesupport", "~> 3"
gem "activemodel", "~> 3"

# Add dependencies to develop your gem here.
# Include everything needed to run rake, tests, features, etc.
group :development do
  gem "rspec", "~> 2.8.0"
  gem "rdoc", "~> 3.12"
  gem "cucumber", ">= 0"
  gem "bundler"
  gem "jeweler", "~> 1.8.3"
  gem "chronic"
end
