source "http://rubygems.org"
# Add dependencies required to use your gem here.

ruby '2.0.0'

gem "activesupport", "~> 4.0.0"
gem "activemodel", "~> 4.0.0"

# Add dependencies to develop your gem here.
# Include everything needed to run rake, tests, features, etc.
group :development, :test do
  gem "rspec", "~> 2.8.0"
  gem "rdoc", "~> 3.12"
  gem "cucumber", ">= 0"
  gem "bundler"
  gem "jeweler", "~> 1.8.3"
  gem "chronic"
end
