# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "holiday"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["James Hunt"]
  s.date = "2012-06-14"
  s.description = "TODO: longer description of your gem"
  s.email = "ohthatjames@googlemail.com"
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "features/employee_requests_holiday.feature",
    "features/step_definitions/employee_requests_holiday_steps.rb",
    "features/support/env.rb",
    "lib/holiday.rb",
    "lib/holiday/add_holiday_request.rb",
    "lib/holiday/employee.rb",
    "lib/holiday/holiday_repository.rb",
    "lib/holiday/holiday_request.rb",
    "spec/holiday/add_holiday_request_spec.rb",
    "spec/holiday/employee_spec.rb",
    "spec/holiday/holiday_repository_spec.rb",
    "spec/holiday/holiday_request_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/ohthatjames/holiday"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "TODO: one-line summary of your gem"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

